/**
 * Two-language UI strings. `t('key', { n: 3 })` interpolates `{n}`. Language is remembered
 * per browser; the default follows the browser language (Turkish or English).
 */
export class I18n {
  /** @type {Record<'tr'|'en', Record<string, string>>} */
  static DICT = {
    tr: {
      'app.name': 'Console',
      'nav.overview': 'Genel bakış', 'nav.notify': 'Bildirim', 'nav.auth': 'Kimlik', 'nav.media': 'Medya', 'nav.gateway': 'Gateway', 'nav.audit': 'Konsol günlüğü', 'nav.admins': 'Yöneticiler', 'nav.account': 'Hesabım', 'nav.services': 'Servisler', 'nav.console': 'Konsol', 'nav.more': 'Diğer',
      'common.search': 'Ara', 'common.refresh': 'Yenile', 'common.cancel': 'Vazgeç', 'common.save': 'Kaydet', 'common.close': 'Kapat', 'common.confirm': 'Onayla', 'common.delete': 'Sil', 'common.copy': 'Kopyala', 'common.copied': 'Kopyalandı', 'common.loadMore': 'Daha fazla yükle', 'common.retry': 'Tekrar dene', 'common.back': 'Geri', 'common.yes': 'Evet', 'common.no': 'Hayır', 'common.all': 'Hepsi', 'common.none': 'yok', 'common.unknown': 'bilinmiyor', 'common.loading': 'Yükleniyor…', 'common.actions': 'İşlemler', 'common.details': 'Ayrıntılar', 'common.status': 'Durum', 'common.created': 'Oluşturuldu', 'common.updated': 'Güncellendi', 'common.name': 'Ad', 'common.email': 'E-posta', 'common.password': 'Şifre', 'common.role': 'Rol', 'common.type': 'Tür', 'common.size': 'Boyut', 'common.id': 'Kimlik', 'common.viewerNote': 'Salt okunur hesap: değişiklik yapamazsınız.', 'common.offline': 'Çevrimdışısınız. Veriler güncel olmayabilir.', 'common.updateAvailable': 'Yeni sürüm hazır.', 'common.reload': 'Yenile', 'common.install': 'Uygulama olarak yükle', 'common.error': 'Bir sorun oluştu', 'common.notFound': 'Sayfa bulunamadı', 'common.notFoundDesc': 'Bu adres konsolda yok.', 'common.goHome': 'Genel bakışa dön', 'common.typeToConfirm': 'Onaylamak için {word} yazın', 'common.optional': 'isteğe bağlı', 'common.showMore': 'Daha fazla göster', 'common.at': 'Zaman', 'common.ip': 'IP',
      'login.title': 'Konsola giriş', 'login.subtitle': 'Yönetici hesabınızla oturum açın.', 'login.submit': 'Giriş yap', 'login.totpTitle': 'İkinci adım', 'login.totpSubtitle': 'Doğrulama uygulamanızdaki 6 haneli kodu girin.', 'login.totpSubmit': 'Doğrula', 'login.code': 'Kod', 'login.locked': 'Hesap kilitli. {s} saniye sonra tekrar deneyin.', 'login.backToLogin': 'Başka hesapla giriş',
      'overview.title': 'Genel bakış', 'overview.desc': 'Tüm servislerin sağlığı ve temel sayılar.', 'overview.healthy': 'Sağlıklı', 'overview.degraded': 'Sorunlu', 'overview.down': 'Erişilemiyor', 'overview.latency': 'gecikme', 'overview.open': 'Aç', 'overview.uptime': 'Çalışma süresi', 'overview.noMetrics': 'Metrik yok',
      'notify.title': 'Bildirim', 'notify.desc': 'E-posta ve webhook kuyruğu.', 'notify.queued': 'Kuyrukta', 'notify.processing': 'İşleniyor', 'notify.sent': 'Gönderildi', 'notify.failed': 'Başarısız', 'notify.oldest': 'En eski bekleyen', 'notify.messages': 'Mesajlar', 'notify.retry': 'Yeniden dene', 'notify.retryDone': 'Mesaj kuyruğa alındı.', 'notify.send': 'Mesaj gönder', 'notify.sendTitle': 'Test mesajı gönder', 'notify.sendDesc': 'Şablonu ve verisini seç; mesaj gerçekten gönderilir.', 'notify.template': 'Şablon', 'notify.to': 'Alıcı', 'notify.data': 'Veri (JSON)', 'notify.sendDone': 'Mesaj kuyruğa alındı: {id}', 'notify.channel': 'Kanal', 'notify.attempts': 'Deneme', 'notify.nextAttempt': 'Sonraki deneme', 'notify.lastError': 'Son hata', 'notify.provider': 'Sağlayıcı kimliği', 'notify.emptyTitle': 'Mesaj yok', 'notify.emptyDesc': 'Bu filtreyle eşleşen mesaj bulunamadı.', 'notify.message': 'Mesaj', 'notify.event': 'Olay', 'notify.url': 'Adres', 'notify.invalidJson': 'Veri geçerli JSON değil.',
      'auth.title': 'Kimlik', 'auth.desc': 'Kullanıcılar, oturumlar ve denetim günlüğü.', 'auth.users': 'Kullanıcılar', 'auth.activeUsers': 'Aktif kullanıcı', 'auth.disabledUsers': 'Devre dışı', 'auth.activeSessions': 'Aktif oturum', 'auth.searchEmail': 'E-posta ile ara', 'auth.createUser': 'Kullanıcı oluştur', 'auth.createDesc': 'Kullanıcıya doğrulama e-postası gönderilir.', 'auth.verified': 'Doğrulanmış', 'auth.unverified': 'Doğrulanmamış', 'auth.locked': 'Kilitli', 'auth.disable': 'Devre dışı bırak', 'auth.enable': 'Etkinleştir', 'auth.disableDesc': 'Kullanıcının tüm oturumları kapanır, giriş yapamaz.', 'auth.deleteUser': 'Kullanıcıyı sil', 'auth.deleteDesc': 'Hesap, oturumlar ve bekleyen bağlantılar kalıcı olarak silinir. Geri alınamaz.', 'auth.sessions': 'Oturumlar', 'auth.revoke': 'Oturumu kapat', 'auth.revokeAll': 'Tüm oturumları kapat', 'auth.revokeAllDesc': 'Kullanıcı tüm cihazlarda çıkış yapar.', 'auth.events': 'Denetim günlüğü', 'auth.resend': 'Doğrulama e-postası gönder', 'auth.resetEmail': 'Şifre sıfırlama e-postası gönder', 'auth.sent': 'E-posta gönderildi.', 'auth.emptyTitle': 'Kullanıcı yok', 'auth.emptyDesc': 'Arama sonucu boş.', 'auth.lastSeen': 'Son görülme', 'auth.expires': 'Bitiş', 'auth.device': 'Cihaz', 'auth.passwordChanged': 'Şifre değişikliği', 'auth.jwks': 'İmza anahtarları (JWKS)', 'auth.noSessions': 'Aktif oturum yok.', 'auth.userCreated': 'Kullanıcı oluşturuldu.', 'auth.userDeleted': 'Kullanıcı silindi.', 'auth.updated': 'Kullanıcı güncellendi.', 'auth.revoked': 'Oturum kapatıldı.', 'auth.revokedAll': '{n} oturum kapatıldı.',
      'media.title': 'Medya', 'media.desc': 'Dosyalar, görüntü varyantları ve yükleme.', 'media.files': 'Dosyalar', 'media.blobs': 'Tekil nesne', 'media.stored': 'Depolanan', 'media.uploads': 'Yükleme', 'media.downloads': 'İndirme', 'media.upload': 'Yükle', 'media.dropHere': 'Dosyaları buraya bırakın veya seçin', 'media.dropHint': 'Görseller yeniden kodlanır, EXIF silinir.', 'media.visibility': 'Görünürlük', 'media.public': 'Herkese açık', 'media.private': 'Özel', 'media.uploaded': 'Yüklendi: {name}', 'media.delete': 'Dosyayı sil', 'media.deleteDesc': 'Dosya hemen erişilemez olur; baytlar {days} gün sonra silinir. Bu süre içinde geri alınabilir.', 'media.restore': 'Geri al', 'media.restored': 'Dosya geri alındı.', 'media.deleted': 'Dosya silindi.', 'media.signedUrl': 'İmzalı bağlantı üret', 'media.ttl': 'Geçerlilik (saniye)', 'media.urls': 'Bağlantılar', 'media.expires': 'Bitiş', 'media.variants': 'Varyantlar', 'media.original': 'Orijinal', 'media.dimensions': 'Boyutlar', 'media.sha': 'SHA-256', 'media.emptyTitle': 'Dosya yok', 'media.emptyDesc': 'Henüz bir şey yüklenmedi.', 'media.rename': 'Yeniden adlandır', 'media.newName': 'Yeni ad', 'media.ticket': 'Yükleme bileti', 'media.ticketDesc': 'Tarayıcıdan doğrudan yükleme için tek kullanımlık adres.', 'media.ticketCreated': 'Bilet oluşturuldu.', 'media.maxBytes': 'En fazla bayt', 'media.grid': 'Izgara', 'media.list': 'Liste', 'media.preview': 'Önizleme', 'media.noPreview': 'Önizleme yok',
      'gateway.title': 'Gateway', 'gateway.desc': 'Yönlendirmeler, upstream sağlığı ve trafik.', 'gateway.routes': 'Yönlendirmeler', 'gateway.route': 'Yönlendirme', 'gateway.requests': 'İstek', 'gateway.errors': 'Upstream hatası', 'gateway.p50': 'p50', 'gateway.p95': 'p95', 'gateway.rejected': 'Reddedilen', 'gateway.rateLimited': 'Hız sınırı', 'gateway.unauthorized': 'Yetkisiz', 'gateway.noRoute': 'Rota yok', 'gateway.upstreams': 'Upstream sağlığı', 'gateway.noMetrics': 'Metrik token tanımlı değil; sadece sağlık gösterilir.', 'gateway.in': 'gelen', 'gateway.out': 'giden',
      'audit.title': 'Konsol günlüğü', 'audit.desc': 'Konsolda kim ne yaptı.', 'audit.action': 'İşlem', 'audit.actor': 'Yapan', 'audit.target': 'Hedef', 'audit.filter': 'İşlem önekiyle filtrele (örn. auth.)', 'audit.emptyTitle': 'Kayıt yok', 'audit.emptyDesc': 'Bu filtreyle eşleşen kayıt bulunamadı.',
      'admins.title': 'Yöneticiler', 'admins.desc': 'Konsola kim girebilir.', 'admins.create': 'Yönetici ekle', 'admins.admin': 'Yönetici', 'admins.viewer': 'İzleyici', 'admins.adminDesc': 'Her şeyi görür ve değiştirir.', 'admins.viewerDesc': 'Sadece görüntüler.', 'admins.disable': 'Devre dışı bırak', 'admins.enable': 'Etkinleştir', 'admins.delete': 'Yöneticiyi sil', 'admins.deleteDesc': 'Hesap kalıcı olarak silinir.', 'admins.resetPassword': 'Şifre belirle', 'admins.resetDesc': 'Kişinin tüm oturumları kapanır; yeni şifreyi güvenli bir yoldan iletin.', 'admins.unlock': 'Kilidi aç', 'admins.totp': '2FA', 'admins.lastLogin': 'Son giriş', 'admins.created': 'Yönetici eklendi.', 'admins.updated': 'Yönetici güncellendi.', 'admins.deleted': 'Yönetici silindi.', 'admins.passwordSet': 'Şifre güncellendi.', 'admins.unlocked': 'Kilit açıldı.', 'admins.you': 'siz',
      'account.title': 'Hesabım', 'account.desc': 'Şifre, iki adımlı doğrulama ve oturumlar.', 'account.password': 'Şifre değiştir', 'account.current': 'Mevcut şifre', 'account.new': 'Yeni şifre', 'account.newHint': 'En az 12 karakter.', 'account.passwordChanged': 'Şifre değiştirildi. Diğer oturumlar kapatıldı.', 'account.totp': 'İki adımlı doğrulama', 'account.totpOn': 'Açık', 'account.totpOff': 'Kapalı', 'account.totpDesc': 'Girişte doğrulama uygulamasından kod istenir. Konsol tüm servis anahtarlarını tuttuğu için açık olması önerilir.', 'account.enableTotp': 'Etkinleştir', 'account.scan': 'Kodu doğrulama uygulamanızla tarayın, sonra üretilen kodu girin.', 'account.secret': 'Elle girmek için anahtar', 'account.totpEnabled': 'İki adımlı doğrulama açıldı.', 'account.disableTotp': 'Kapat', 'account.disableTotpDesc': 'Kapatmak için şifreniz ve geçerli bir kod gerekir.', 'account.totpDisabled': 'İki adımlı doğrulama kapatıldı.', 'account.sessions': 'Oturumlarım', 'account.thisDevice': 'bu cihaz', 'account.logoutOthers': 'Diğer oturumları kapat', 'account.loggedOutOthers': '{n} oturum kapatıldı.', 'account.theme': 'Görünüm', 'account.themeSystem': 'Sistem', 'account.themeLight': 'Açık', 'account.themeDark': 'Koyu', 'account.language': 'Dil', 'account.logout': 'Çıkış yap',
      'ev.title': 'Denetim olayları', 'ev.desc': 'Servislerin gönderdiği olaylar, zincir doğrulama ve dışa aktarma.', 'ev.events': 'Olaylar', 'ev.totalEvents': 'Toplam olay', 'ev.window': 'Son {h} saat', 'ev.failures': 'Başarısız', 'ev.deniedCount': 'Reddedilen', 'ev.lastHour': 'Son 1 saat', 'ev.headSeq': 'Zincir ucu', 'ev.dbSize': 'Veritabanı', 'ev.oldest': 'En eski kayıt', 'ev.success': 'Başarılı', 'ev.failure': 'Başarısız', 'ev.denied': 'Reddedildi', 'ev.action': 'İşlem', 'ev.actor': 'Yapan', 'ev.target': 'Hedef', 'ev.source': 'Kaynak', 'ev.outcome': 'Sonuç', 'ev.requestId': 'İstek kimliği', 'ev.userAgent': 'İstemci', 'ev.meta': 'Ayrıntılar', 'ev.receivedAt': 'Alındı', 'ev.hash': 'Özet', 'ev.prevHash': 'Önceki özet', 'ev.seq': 'Sıra', 'ev.clientId': 'İstemci kimliği', 'ev.filters': 'Filtreler', 'ev.actionPrefix': 'İşlem öneki (örn. auth.)', 'ev.from': 'Başlangıç', 'ev.to': 'Bitiş', 'ev.clear': 'Filtreleri temizle', 'ev.apply': 'Uygula', 'ev.verify': 'Zinciri doğrula', 'ev.verifying': 'Doğrulanıyor…', 'ev.verifyOk': '{n} olay doğrulandı, zincir sağlam.', 'ev.verifyBroken': 'Zincir {seq} numaralı olayda kırık: {reason}', 'ev.chainOk': 'Zincir sağlam', 'ev.chainBroken': 'Zincir kırık', 'ev.export': 'Dışa aktar', 'ev.exportTitle': 'Olayları dışa aktar', 'ev.exportDesc': 'Geçerli filtreyle eşleşen olaylar en eskiden yeniye akış olarak indirilir. Servis tek seferde en fazla EXPORT_MAX_ROWS satır verir; büyük aralıkları tarihe göre bölün. İndirme konsolun denetim günlüğüne yazılır.', 'ev.format': 'Biçim', 'ev.download': 'İndir', 'ev.activeFilters': '{n} filtre etkin', 'ev.noFilters': 'Filtre yok: tüm olaylar', 'ev.topActions': 'En sık işlemler', 'ev.topFailures': 'En sık hatalar', 'ev.bySource': 'Kaynağa göre', 'ev.topActors': 'En aktif aktörler', 'ev.emptyTitle': 'Olay yok', 'ev.emptyDesc': 'Bu filtreyle eşleşen olay bulunamadı.', 'ev.event': 'Olay', 'ev.eventsOfActor': 'Bu aktörün olayları', 'ev.eventsOfTarget': 'Bu hedefin olayları', 'ev.sameRequest': 'Aynı istekteki olaylar', 'ev.noStats': 'Bu pencerede olay yok.', 'ev.type': 'tür', 'ev.at': 'Olay zamanı', 'ev.viaRedaction': 'Gizli alanlar servis tarafından maskelendi.',
      'sl.title': 'Kısa bağlantılar', 'sl.desc': 'Yönlendirmeler, tıklama istatistikleri ve QR kodları.', 'sl.links': 'Bağlantılar', 'sl.link': 'Bağlantı', 'sl.activeLinks': 'Aktif bağlantı', 'sl.inactiveLinks': 'Pasif', 'sl.clicks': 'Tıklama', 'sl.clicksLastHour': 'Son 1 saat', 'sl.clicksWindow': 'Son {d} gün', 'sl.visitors': 'Tekil ziyaretçi', 'sl.bots': 'Bot', 'sl.topLinks': 'En çok tıklanan', 'sl.create': 'Bağlantı oluştur', 'sl.createDesc': 'Hedef adres zorunlu; kısa kod boş bırakılırsa rastgele üretilir.', 'sl.created': 'Bağlantı oluşturuldu: {code}', 'sl.updated': 'Bağlantı güncellendi.', 'sl.deleted': 'Bağlantı silindi.', 'sl.url': 'Hedef adres', 'sl.slug': 'Kısa kod', 'sl.slugHint': '3–64 karakter: harf, rakam, _ ve -. Boş bırakılırsa rastgele.', 'sl.shortUrl': 'Kısa adres', 'sl.tags': 'Etiketler', 'sl.tagsHint': 'Virgülle ayır', 'sl.note': 'Not', 'sl.expiresAt': 'Son geçerlilik', 'sl.maxClicks': 'Tıklama sınırı', 'sl.remaining': 'kalan {n}', 'sl.permanent': 'Kalıcı yönlendirme (301)', 'sl.permanentHint': 'Tarayıcılar önbelleğe alır; hedef sonradan değişmeyecekse seçin.', 'sl.temporary': '302', 'sl.status': 'Durum', 'sl.active': 'Aktif', 'sl.disabled': 'Devre dışı', 'sl.expired': 'Süresi doldu', 'sl.exhausted': 'Sınıra ulaştı', 'sl.disable': 'Devre dışı bırak', 'sl.disableDesc': 'Ziyaretçiler 410 alır; bağlantı ve istatistikleri kalır, tekrar açılabilir.', 'sl.enable': 'Etkinleştir', 'sl.delete': 'Bağlantıyı sil', 'sl.deleteDesc': 'Kod boşa çıkar, tıklama geçmişi silinir. Basılı QR kodlar çalışmaz.', 'sl.edit': 'Düzenle', 'sl.search': 'Kod veya adres ara', 'sl.tag': 'Etiket', 'sl.emptyTitle': 'Bağlantı yok', 'sl.emptyDesc': 'Bu filtreyle eşleşen bağlantı bulunamadı.', 'sl.lastClick': 'Son tıklama', 'sl.never': 'hiç', 'sl.preview': 'Önizleme sayfası', 'sl.open': 'Hedefi aç', 'sl.qr': 'QR kodu', 'sl.qrHint': 'Kısa adresi kodlar. PNG indir; baskı için servisin SVG çıktısını kullan.', 'sl.download': 'PNG indir', 'sl.byDay': 'Güne göre tıklama', 'sl.byReferrer': 'Yönlendiren siteler', 'sl.direct': 'doğrudan / QR', 'sl.byDevice': 'Cihaz', 'sl.recent': 'Son tıklamalar', 'sl.visitor': 'Ziyaretçi', 'sl.referrer': 'Yönlendiren', 'sl.device': 'Cihaz', 'sl.noClicks': 'Bu pencerede tıklama yok.', 'sl.days': '{d} gün', 'sl.createdBy': 'Oluşturan', 'sl.invalidDate': 'Tarih geçersiz.',
      'fl.title': 'Özellik anahtarları', 'fl.desc': 'Ortam başına anahtarlar, kademeli dağıtım ve hedefleme kuralları.', 'fl.flags': 'Anahtarlar', 'fl.flag': 'Anahtar', 'fl.key': 'Anahtar', 'fl.keyHint': 'Küçük harf parçalar; ayraç . - _ (örn. checkout.new). Sonradan değişmez.', 'fl.kind': 'Tür', 'fl.value': 'Açıkken değer', 'fl.offValue': 'Kapalıyken değer', 'fl.enableEverywhere': 'Tüm ortamlarda hemen açık başlasın', 'fl.description': 'Açıklama', 'fl.create': 'Anahtar oluştur', 'fl.created': 'Anahtar oluşturuldu: {key}', 'fl.edit': 'Düzenle', 'fl.updated': 'Anahtar güncellendi.', 'fl.saved': '{env} kaydedildi.', 'fl.discard': 'Vazgeç', 'fl.enabledIn': '{key} · {env} açıldı.', 'fl.disabledIn': '{key} · {env} kapatıldı.', 'fl.copied': '{from} → {to} kopyalandı.', 'fl.copyTo': 'Kopyala', 'fl.active': 'Aktif', 'fl.archived': 'Arşiv', 'fl.archive': 'Arşivle', 'fl.archiveDesc': 'Anahtar değerlendirmelerden ve snapshot\'tan çıkar; uygulamalar bu anahtarı istediğinde null alır. Geri alınabilir.', 'fl.unarchive': 'Arşivden çıkar', 'fl.unarchived': 'Anahtar arşivden çıkarıldı.', 'fl.delete': 'Anahtarı sil', 'fl.deleteDesc': 'Tüm ortam durumları silinir; geçmiş kalır. Uygulamalar null alır.', 'fl.deleted': 'Anahtar silindi.', 'fl.reshuffle': 'Kovaları yeniden dağıt', 'fl.reshuffleDesc': 'Yüzdelik dağıtımdaki kullanıcılar yeniden kura çekilir; kimin içeride olduğu değişir.', 'fl.reshuffled': 'Kovalar yeniden dağıtıldı.', 'fl.enabledShort': 'açık', 'fl.evals': 'değerlendirme', 'fl.search': 'Anahtar veya açıklama ara', 'fl.emptyTitle': 'Anahtar yok', 'fl.emptyDesc': 'Bu filtreyle eşleşen anahtar bulunamadı.', 'fl.rulesShort': 'kural', 'fl.rules': 'Hedefleme kuralları', 'fl.noRules': 'Kural yok.', 'fl.moveUp': 'Yukarı taşı', 'fl.moveDown': 'Aşağı taşı', 'fl.duplicateId': 'aynı id iki kez', 'fl.addRule': 'Kural ekle', 'fl.ruleName': 'Kural adı', 'fl.userIds': 'Kullanıcı kimlikleri', 'fl.emails': 'E-postalar', 'fl.attrs': 'Özellikler', 'fl.serves': 'Sunulan değer', 'fl.percentage': 'Dağıtım yüzdesi', 'fl.percentageHint': 'Kimliği olan kullanıcıların bu yüzdesi "açıkken değer"i alır; kalanlar kapalı değeri. Kurallar önce uygulanır.', 'fl.environment': 'Ortam', 'fl.userId': 'Kullanıcı kimliği', 'fl.evaluate': 'Değerlendir', 'fl.evaluateDesc': 'Belirli bir kullanıcı için bu anahtarın ne döndüğünü ve nedenini gör.', 'fl.changed': 'Değişen', 'fl.invalidJson': 'Geçerli JSON değil.', 'fl.reason.disabled': 'kapalı', 'fl.reason.rule': 'kural', 'fl.reason.rollout': 'dağıtım içinde', 'fl.reason.excluded': 'dağıtım dışında', 'fl.reason.default': 'varsayılan', 'fl.reason.missing': 'yok', 'history.title': 'Geçmiş',
      'account.logoutDesc': 'Bu cihazdaki oturum kapanır; tekrar giriş yapmanız gerekir.', 'account.logoutOthersDesc': 'Bu cihaz dışındaki tüm oturumlar kapanır.', 'admins.disableDesc': 'Kişi konsola giremez; tüm oturumları kapanır. Tekrar etkinleştirilebilir.', 'admins.toViewerDesc': 'Kişi izleyici olur: her şeyi görür, hiçbir şeyi değiştiremez.', 'admins.toAdminDesc': 'Kişi yönetici olur: her şeyi görür ve değiştirir.', 'auth.revokeDesc': 'Kullanıcı bu cihazda çıkış yapar; diğer oturumları kalır.', 'confirm.irreversible': 'Bu işlem geri alınamaz.',
      'poll.label': 'Otomatik yenile', 'poll.off': 'Kapalı', 'poll.saved': 'Otomatik yenileme ayarı kaydedildi.', 'poll.viewer': 'Bu ayarı yalnızca yöneticiler değiştirir.', 'poll.hint': 'Yalnızca bu sayfa açık ve sekme görünürken çalışır.', 'poll.inFlight': 'istek sürüyor', 'poll.slowed': 'etkin {s} s', 'poll.slowedHint': 'Servis yavaş yanıtlıyor (ort. {avg} s). Aralık, ortalamanın 1,3 katından az olmayacak şekilde otomatik uzatıldı.', 'poll.configured': 'Ayar', 'poll.effective': 'Etkin aralık', 'poll.avg': 'Ortalama', 'poll.last': 'Son', 'poll.runs': 'Çalışma', 'poll.errors': 'hata', 'poll.coalesced': 'birleştirilen', 'poll.next': 'sonraki {s} s', 'poll.paused': 'duraklatıldı', 'poll.lastTen': 'Son 10 isteğin süresi',
    },
    en: {
      'app.name': 'Console',
      'nav.overview': 'Overview', 'nav.notify': 'Notify', 'nav.auth': 'Auth', 'nav.media': 'Media', 'nav.gateway': 'Gateway', 'nav.audit': 'Console log', 'nav.admins': 'Admins', 'nav.account': 'Account', 'nav.services': 'Services', 'nav.console': 'Console', 'nav.more': 'More',
      'common.search': 'Search', 'common.refresh': 'Refresh', 'common.cancel': 'Cancel', 'common.save': 'Save', 'common.close': 'Close', 'common.confirm': 'Confirm', 'common.delete': 'Delete', 'common.copy': 'Copy', 'common.copied': 'Copied', 'common.loadMore': 'Load more', 'common.retry': 'Retry', 'common.back': 'Back', 'common.yes': 'Yes', 'common.no': 'No', 'common.all': 'All', 'common.none': 'none', 'common.unknown': 'unknown', 'common.loading': 'Loading…', 'common.actions': 'Actions', 'common.details': 'Details', 'common.status': 'Status', 'common.created': 'Created', 'common.updated': 'Updated', 'common.name': 'Name', 'common.email': 'Email', 'common.password': 'Password', 'common.role': 'Role', 'common.type': 'Type', 'common.size': 'Size', 'common.id': 'ID', 'common.viewerNote': 'Read-only account: you cannot make changes.', 'common.offline': 'You are offline. Data may be stale.', 'common.updateAvailable': 'A new version is ready.', 'common.reload': 'Reload', 'common.install': 'Install as app', 'common.error': 'Something went wrong', 'common.notFound': 'Page not found', 'common.notFoundDesc': 'This address does not exist in the console.', 'common.goHome': 'Back to overview', 'common.typeToConfirm': 'Type {word} to confirm', 'common.optional': 'optional', 'common.showMore': 'Show more', 'common.at': 'Time', 'common.ip': 'IP',
      'login.title': 'Sign in to Console', 'login.subtitle': 'Use your administrator account.', 'login.submit': 'Sign in', 'login.totpTitle': 'Second step', 'login.totpSubtitle': 'Enter the 6-digit code from your authenticator app.', 'login.totpSubmit': 'Verify', 'login.code': 'Code', 'login.locked': 'Account locked. Try again in {s} seconds.', 'login.backToLogin': 'Use another account',
      'overview.title': 'Overview', 'overview.desc': 'Health and headline numbers for every service.', 'overview.healthy': 'Healthy', 'overview.degraded': 'Degraded', 'overview.down': 'Unreachable', 'overview.latency': 'latency', 'overview.open': 'Open', 'overview.uptime': 'Uptime', 'overview.noMetrics': 'No metrics',
      'notify.title': 'Notify', 'notify.desc': 'Email and webhook queue.', 'notify.queued': 'Queued', 'notify.processing': 'Processing', 'notify.sent': 'Sent', 'notify.failed': 'Failed', 'notify.oldest': 'Oldest waiting', 'notify.messages': 'Messages', 'notify.retry': 'Retry', 'notify.retryDone': 'Message re-queued.', 'notify.send': 'Send message', 'notify.sendTitle': 'Send a test message', 'notify.sendDesc': 'Pick a template and data; the message is really sent.', 'notify.template': 'Template', 'notify.to': 'Recipient', 'notify.data': 'Data (JSON)', 'notify.sendDone': 'Message queued: {id}', 'notify.channel': 'Channel', 'notify.attempts': 'Attempts', 'notify.nextAttempt': 'Next attempt', 'notify.lastError': 'Last error', 'notify.provider': 'Provider id', 'notify.emptyTitle': 'No messages', 'notify.emptyDesc': 'Nothing matches this filter.', 'notify.message': 'Message', 'notify.event': 'Event', 'notify.url': 'URL', 'notify.invalidJson': 'Data is not valid JSON.',
      'auth.title': 'Auth', 'auth.desc': 'Users, sessions and audit trail.', 'auth.users': 'Users', 'auth.activeUsers': 'Active users', 'auth.disabledUsers': 'Disabled', 'auth.activeSessions': 'Active sessions', 'auth.searchEmail': 'Search by email', 'auth.createUser': 'Create user', 'auth.createDesc': 'A verification email is sent to the user.', 'auth.verified': 'Verified', 'auth.unverified': 'Unverified', 'auth.locked': 'Locked', 'auth.disable': 'Disable', 'auth.enable': 'Enable', 'auth.disableDesc': 'All sessions end and the user cannot sign in.', 'auth.deleteUser': 'Delete user', 'auth.deleteDesc': 'The account, its sessions and pending links are deleted permanently.', 'auth.sessions': 'Sessions', 'auth.revoke': 'Revoke session', 'auth.revokeAll': 'Revoke all sessions', 'auth.revokeAllDesc': 'The user is signed out on every device.', 'auth.events': 'Audit trail', 'auth.resend': 'Send verification email', 'auth.resetEmail': 'Send password reset email', 'auth.sent': 'Email sent.', 'auth.emptyTitle': 'No users', 'auth.emptyDesc': 'The search returned nothing.', 'auth.lastSeen': 'Last seen', 'auth.expires': 'Expires', 'auth.device': 'Device', 'auth.passwordChanged': 'Password changed', 'auth.jwks': 'Signing keys (JWKS)', 'auth.noSessions': 'No active sessions.', 'auth.userCreated': 'User created.', 'auth.userDeleted': 'User deleted.', 'auth.updated': 'User updated.', 'auth.revoked': 'Session revoked.', 'auth.revokedAll': '{n} sessions revoked.',
      'media.title': 'Media', 'media.desc': 'Files, image variants and uploads.', 'media.files': 'Files', 'media.blobs': 'Unique objects', 'media.stored': 'Stored', 'media.uploads': 'Uploads', 'media.downloads': 'Downloads', 'media.upload': 'Upload', 'media.dropHere': 'Drop files here or choose', 'media.dropHint': 'Images are re-encoded and stripped of EXIF.', 'media.visibility': 'Visibility', 'media.public': 'Public', 'media.private': 'Private', 'media.uploaded': 'Uploaded: {name}', 'media.delete': 'Delete file', 'media.deleteDesc': 'The file becomes unreachable now; bytes are removed after {days} days. It can be restored until then.', 'media.restore': 'Restore', 'media.restored': 'File restored.', 'media.deleted': 'File deleted.', 'media.signedUrl': 'Generate signed link', 'media.ttl': 'Validity (seconds)', 'media.urls': 'Links', 'media.expires': 'Expires', 'media.variants': 'Variants', 'media.original': 'Original', 'media.dimensions': 'Dimensions', 'media.sha': 'SHA-256', 'media.emptyTitle': 'No files', 'media.emptyDesc': 'Nothing has been uploaded yet.', 'media.rename': 'Rename', 'media.newName': 'New name', 'media.ticket': 'Upload ticket', 'media.ticketDesc': 'Single-use address for direct browser uploads.', 'media.ticketCreated': 'Ticket created.', 'media.maxBytes': 'Max bytes', 'media.grid': 'Grid', 'media.list': 'List', 'media.preview': 'Preview', 'media.noPreview': 'No preview',
      'gateway.title': 'Gateway', 'gateway.desc': 'Routes, upstream health and traffic.', 'gateway.routes': 'Routes', 'gateway.route': 'Route', 'gateway.requests': 'Requests', 'gateway.errors': 'Upstream errors', 'gateway.p50': 'p50', 'gateway.p95': 'p95', 'gateway.rejected': 'Rejected', 'gateway.rateLimited': 'Rate limited', 'gateway.unauthorized': 'Unauthorized', 'gateway.noRoute': 'No route', 'gateway.upstreams': 'Upstream health', 'gateway.noMetrics': 'No metrics token configured; only health is shown.', 'gateway.in': 'in', 'gateway.out': 'out',
      'audit.title': 'Console log', 'audit.desc': 'Who did what in the console.', 'audit.action': 'Action', 'audit.actor': 'Actor', 'audit.target': 'Target', 'audit.filter': 'Filter by action prefix (e.g. auth.)', 'audit.emptyTitle': 'No entries', 'audit.emptyDesc': 'Nothing matches this filter.',
      'admins.title': 'Admins', 'admins.desc': 'Who can sign in to the console.', 'admins.create': 'Add admin', 'admins.admin': 'Admin', 'admins.viewer': 'Viewer', 'admins.adminDesc': 'Sees and changes everything.', 'admins.viewerDesc': 'Read-only.', 'admins.disable': 'Disable', 'admins.enable': 'Enable', 'admins.delete': 'Delete admin', 'admins.deleteDesc': 'The account is deleted permanently.', 'admins.resetPassword': 'Set password', 'admins.resetDesc': 'All their sessions end; hand over the new password through a secure channel.', 'admins.unlock': 'Unlock', 'admins.totp': '2FA', 'admins.lastLogin': 'Last login', 'admins.created': 'Admin added.', 'admins.updated': 'Admin updated.', 'admins.deleted': 'Admin deleted.', 'admins.passwordSet': 'Password updated.', 'admins.unlocked': 'Unlocked.', 'admins.you': 'you',
      'account.title': 'Account', 'account.desc': 'Password, two-factor authentication and sessions.', 'account.password': 'Change password', 'account.current': 'Current password', 'account.new': 'New password', 'account.newHint': 'At least 12 characters.', 'account.passwordChanged': 'Password changed. Other sessions were signed out.', 'account.totp': 'Two-factor authentication', 'account.totpOn': 'On', 'account.totpOff': 'Off', 'account.totpDesc': 'Sign-in asks for a code from your authenticator app. Recommended: the console holds every service key.', 'account.enableTotp': 'Enable', 'account.scan': 'Scan the code with your authenticator app, then enter the generated code.', 'account.secret': 'Key for manual entry', 'account.totpEnabled': 'Two-factor authentication enabled.', 'account.disableTotp': 'Disable', 'account.disableTotpDesc': 'Disabling needs your password and a valid code.', 'account.totpDisabled': 'Two-factor authentication disabled.', 'account.sessions': 'My sessions', 'account.thisDevice': 'this device', 'account.logoutOthers': 'Sign out other sessions', 'account.loggedOutOthers': '{n} sessions signed out.', 'account.theme': 'Appearance', 'account.themeSystem': 'System', 'account.themeLight': 'Light', 'account.themeDark': 'Dark', 'account.language': 'Language', 'account.logout': 'Sign out',
      'ev.title': 'Audit events', 'ev.desc': 'Events pushed by the services, chain verification and export.', 'ev.events': 'Events', 'ev.totalEvents': 'Total events', 'ev.window': 'Last {h} hours', 'ev.failures': 'Failures', 'ev.deniedCount': 'Denied', 'ev.lastHour': 'Last hour', 'ev.headSeq': 'Chain head', 'ev.dbSize': 'Database', 'ev.oldest': 'Oldest record', 'ev.success': 'Success', 'ev.failure': 'Failure', 'ev.denied': 'Denied', 'ev.action': 'Action', 'ev.actor': 'Actor', 'ev.target': 'Target', 'ev.source': 'Source', 'ev.outcome': 'Outcome', 'ev.requestId': 'Request id', 'ev.userAgent': 'User agent', 'ev.meta': 'Details', 'ev.receivedAt': 'Received', 'ev.hash': 'Hash', 'ev.prevHash': 'Previous hash', 'ev.seq': 'Seq', 'ev.clientId': 'Client id', 'ev.filters': 'Filters', 'ev.actionPrefix': 'Action prefix (e.g. auth.)', 'ev.from': 'From', 'ev.to': 'To', 'ev.clear': 'Clear filters', 'ev.apply': 'Apply', 'ev.verify': 'Verify chain', 'ev.verifying': 'Verifying…', 'ev.verifyOk': '{n} events verified, chain intact.', 'ev.verifyBroken': 'Chain broken at event {seq}: {reason}', 'ev.chainOk': 'Chain intact', 'ev.chainBroken': 'Chain broken', 'ev.export': 'Export', 'ev.exportTitle': 'Export events', 'ev.exportDesc': 'Events matching the current filter are streamed oldest first. The service returns at most EXPORT_MAX_ROWS rows per call; split large ranges by date. The download is recorded in the console audit log.', 'ev.format': 'Format', 'ev.download': 'Download', 'ev.activeFilters': '{n} filters active', 'ev.noFilters': 'No filters: all events', 'ev.topActions': 'Top actions', 'ev.topFailures': 'Top failures', 'ev.bySource': 'By source', 'ev.topActors': 'Most active actors', 'ev.emptyTitle': 'No events', 'ev.emptyDesc': 'Nothing matches this filter.', 'ev.event': 'Event', 'ev.eventsOfActor': 'Events of this actor', 'ev.eventsOfTarget': 'Events on this target', 'ev.sameRequest': 'Events in the same request', 'ev.noStats': 'No events in this window.', 'ev.type': 'type', 'ev.at': 'Event time', 'ev.viaRedaction': 'Sensitive fields were redacted by the service.',
      'sl.title': 'Short links', 'sl.desc': 'Redirects, click statistics and QR codes.', 'sl.links': 'Links', 'sl.link': 'Link', 'sl.activeLinks': 'Active links', 'sl.inactiveLinks': 'Inactive', 'sl.clicks': 'Clicks', 'sl.clicksLastHour': 'Last hour', 'sl.clicksWindow': 'Last {d} days', 'sl.visitors': 'Unique visitors', 'sl.bots': 'Bots', 'sl.topLinks': 'Most clicked', 'sl.create': 'Create link', 'sl.createDesc': 'Destination is required; leave the code empty for a random one.', 'sl.created': 'Link created: {code}', 'sl.updated': 'Link updated.', 'sl.deleted': 'Link deleted.', 'sl.url': 'Destination', 'sl.slug': 'Short code', 'sl.slugHint': '3–64 characters: letters, digits, _ and -. Random when empty.', 'sl.shortUrl': 'Short URL', 'sl.tags': 'Tags', 'sl.tagsHint': 'Comma separated', 'sl.note': 'Note', 'sl.expiresAt': 'Expires', 'sl.maxClicks': 'Click limit', 'sl.remaining': '{n} left', 'sl.permanent': 'Permanent redirect (301)', 'sl.permanentHint': 'Browsers cache it; pick only if the destination will not change.', 'sl.temporary': '302', 'sl.status': 'Status', 'sl.active': 'Active', 'sl.disabled': 'Disabled', 'sl.expired': 'Expired', 'sl.exhausted': 'Limit reached', 'sl.disable': 'Disable', 'sl.disableDesc': 'Visitors get 410; the link and its statistics stay and it can be re-enabled.', 'sl.enable': 'Enable', 'sl.delete': 'Delete link', 'sl.deleteDesc': 'The code becomes free and the click history is removed. Printed QR codes stop working.', 'sl.edit': 'Edit', 'sl.search': 'Search code or destination', 'sl.tag': 'Tag', 'sl.emptyTitle': 'No links', 'sl.emptyDesc': 'Nothing matches this filter.', 'sl.lastClick': 'Last click', 'sl.never': 'never', 'sl.preview': 'Preview page', 'sl.open': 'Open destination', 'sl.qr': 'QR code', 'sl.qrHint': 'Encodes the short URL. Download the PNG; use the service\'s SVG output for print.', 'sl.download': 'Download PNG', 'sl.byDay': 'Clicks per day', 'sl.byReferrer': 'Referring sites', 'sl.direct': 'direct / QR', 'sl.byDevice': 'Devices', 'sl.recent': 'Recent clicks', 'sl.visitor': 'Visitor', 'sl.referrer': 'Referrer', 'sl.device': 'Device', 'sl.noClicks': 'No clicks in this window.', 'sl.days': '{d} days', 'sl.createdBy': 'Created by', 'sl.invalidDate': 'Invalid date.',
      'fl.title': 'Feature flags', 'fl.desc': 'Flags per environment, gradual rollouts and targeting rules.', 'fl.flags': 'Flags', 'fl.flag': 'Flag', 'fl.key': 'Key', 'fl.keyHint': 'Lower-case segments joined by . - _ (e.g. checkout.new). Cannot change later.', 'fl.kind': 'Kind', 'fl.value': 'Value when on', 'fl.offValue': 'Value when off', 'fl.enableEverywhere': 'Start enabled in every environment', 'fl.description': 'Description', 'fl.create': 'Create flag', 'fl.created': 'Flag created: {key}', 'fl.edit': 'Edit', 'fl.updated': 'Flag updated.', 'fl.saved': '{env} saved.', 'fl.discard': 'Discard', 'fl.enabledIn': '{key} · {env} enabled.', 'fl.disabledIn': '{key} · {env} disabled.', 'fl.copied': 'Copied {from} → {to}.', 'fl.copyTo': 'Copy to', 'fl.active': 'Active', 'fl.archived': 'Archived', 'fl.archive': 'Archive', 'fl.archiveDesc': 'The flag leaves evaluations and snapshots; applications asking for it get null. Reversible.', 'fl.unarchive': 'Unarchive', 'fl.unarchived': 'Flag unarchived.', 'fl.delete': 'Delete flag', 'fl.deleteDesc': 'Every environment state is removed; history stays. Applications get null.', 'fl.deleted': 'Flag deleted.', 'fl.reshuffle': 'Reshuffle buckets', 'fl.reshuffleDesc': 'Users in percentage rollouts are drawn again; who is inside changes.', 'fl.reshuffled': 'Buckets reshuffled.', 'fl.enabledShort': 'on', 'fl.evals': 'evaluations', 'fl.search': 'Search key or description', 'fl.emptyTitle': 'No flags', 'fl.emptyDesc': 'Nothing matches this filter.', 'fl.rulesShort': 'rules', 'fl.rules': 'Targeting rules', 'fl.noRules': 'No rules.', 'fl.moveUp': 'Move up', 'fl.moveDown': 'Move down', 'fl.duplicateId': 'duplicate id', 'fl.addRule': 'Add rule', 'fl.ruleName': 'Rule name', 'fl.userIds': 'User ids', 'fl.emails': 'Emails', 'fl.attrs': 'Attributes', 'fl.serves': 'Serves', 'fl.percentage': 'Rollout percentage', 'fl.percentageHint': 'This share of identified users gets the "value when on"; the rest get the off value. Rules apply first.', 'fl.environment': 'Environment', 'fl.userId': 'User id', 'fl.evaluate': 'Evaluate', 'fl.evaluateDesc': 'See what this flag returns for a specific user, and why.', 'fl.changed': 'Changed', 'fl.invalidJson': 'Not valid JSON.', 'fl.reason.disabled': 'disabled', 'fl.reason.rule': 'rule', 'fl.reason.rollout': 'in rollout', 'fl.reason.excluded': 'outside rollout', 'fl.reason.default': 'default', 'fl.reason.missing': 'missing', 'history.title': 'History',
      'account.logoutDesc': 'This device is signed out; you will have to sign in again.', 'account.logoutOthersDesc': 'Every session except this device is signed out.', 'admins.disableDesc': 'The person cannot sign in and all their sessions end. Can be re-enabled.', 'admins.toViewerDesc': 'The person becomes a viewer: sees everything, changes nothing.', 'admins.toAdminDesc': 'The person becomes an admin: sees and changes everything.', 'auth.revokeDesc': 'The user is signed out on that device; other sessions stay.', 'confirm.irreversible': 'This cannot be undone.',
      'poll.label': 'Auto-refresh', 'poll.off': 'Off', 'poll.saved': 'Auto-refresh setting saved.', 'poll.viewer': 'Only administrators change this setting.', 'poll.hint': 'Runs only while this page is open and the tab is visible.', 'poll.inFlight': 'request in flight', 'poll.slowed': 'effective {s} s', 'poll.slowedHint': 'The service answers slowly (avg {avg} s). The interval was stretched automatically to at least 1.3× the average.', 'poll.configured': 'Setting', 'poll.effective': 'Effective interval', 'poll.avg': 'Average', 'poll.last': 'Last', 'poll.runs': 'Runs', 'poll.errors': 'errors', 'poll.coalesced': 'coalesced', 'poll.next': 'next in {s} s', 'poll.paused': 'paused', 'poll.lastTen': 'Duration of the last 10 requests',
    },
  };

  constructor() {
    /** @type {'tr'|'en'} */
    this.lang = $state(I18n.#initial());
    document.documentElement.lang = this.lang;
  }

  static #initial() {
    try {
      const saved = localStorage.getItem('console.lang');
      if (saved === 'tr' || saved === 'en') return saved;
    } catch { /* storage unavailable */ }
    return navigator.language.toLowerCase().startsWith('tr') ? 'tr' : 'en';
  }

  /** @param {'tr'|'en'} lang */
  set(lang) {
    this.lang = lang;
    document.documentElement.lang = lang;
    try { localStorage.setItem('console.lang', lang); } catch { /* ignore */ }
  }

  /**
   * @param {string} key
   * @param {Record<string, string|number>} [vars]
   */
  t = (key, vars) => {
    let s = I18n.DICT[this.lang][key] ?? I18n.DICT.en[key] ?? key;
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v));
    return s;
  };
}

export const i18n = new I18n();
export const t = i18n.t;
